/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package actividad2_sergioescobar_lp4;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
/**
 *
 * @author alexi
 */
public class Deposito_JFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Deposito_JFrame.class.getName());

    /**
     * Creates new form Deposito_JFrame
     */
    public Deposito_JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfDepositar = new javax.swing.JTextField();
        jbtnSalirDepositar = new javax.swing.JButton();
        jbtnDepositar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("DEPÓSITO");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Cantidad a depositar:");

        jtfDepositar.setText("$");
        jtfDepositar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfDepositarFocusLost(evt);
            }
        });
        jtfDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDepositarActionPerformed(evt);
            }
        });

        jbtnSalirDepositar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jbtnSalirDepositar.setText("SALIR");
        jbtnSalirDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirDepositarActionPerformed(evt);
            }
        });

        jbtnDepositar1.setBackground(new java.awt.Color(153, 153, 153));
        jbtnDepositar1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jbtnDepositar1.setForeground(new java.awt.Color(255, 255, 255));
        jbtnDepositar1.setText("DEPOSITAR");
        jbtnDepositar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDepositar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(153, 153, 153))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(114, 114, 114))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jbtnSalirDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jbtnDepositar1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(53, 53, 53)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jtfDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSalirDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnDepositar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfDepositarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfDepositarFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDepositarFocusLost

    private void jtfDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDepositarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDepositarActionPerformed

    private void jbtnSalirDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirDepositarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbtnSalirDepositarActionPerformed

    private void jbtnDepositar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDepositar1ActionPerformed
        // TODO add your handling code here:
        Connection con = null;
        PreparedStatement pstmt = null;
        
        try {
        Conexion conexion = new Conexion(); 
        con = conexion.getConnection();
        
        String texto = jtfDepositar.getText().trim().replace("$", "");
        float monto = Float.parseFloat(texto);
        
        if (monto <= 0) {
            JOptionPane.showMessageDialog(null, "El monto debe ser mayor a cero.");
            return;
        }
        
        String sql = "UPDATE cuenta SET saldo = saldo + ? WHERE id = 1";

        pstmt = con.prepareStatement(sql);
        pstmt.setFloat(1, monto);

        int filas = pstmt.executeUpdate();

        if (filas > 0) {
            JOptionPane.showMessageDialog(this, "Depósito realizado con éxito.");
            jtfDepositar.setText("$");
        } else {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al depositar en la cuenta.");
        }

        con.close();
        
        int respuesta = JOptionPane.showConfirmDialog(
        this,
        "¿Deseas realizar otro depósito?",
        "Depositar nuevamente",
        JOptionPane.YES_NO_OPTION
        );
        
        if (respuesta == JOptionPane.YES_OPTION) {
            jtfDepositar.setText("$");
        } else {
        this.dispose();
        };
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Ingresa un número válido en el campo de depósito.");
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al realizar el depósito: " + e.getMessage());
    }
}
        
       /*
        int respuesta = JOptionPane.showConfirmDialog(
        this,
        "¿Deseas realizar otro depósito?",
        "Depositar nuevamente",
        JOptionPane.YES_NO_OPTION
    );
        if (respuesta == JOptionPane.YES_OPTION) {
            jtfDepositar.setText("$");
        } else {
        this.dispose();
    };
        
    }//GEN-LAST:event_jbtnDepositar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Deposito_JFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbtnDepositar1;
    private javax.swing.JButton jbtnSalirDepositar;
    private javax.swing.JTextField jtfDepositar;
    // End of variables declaration//GEN-END:variables
}
