/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package actividad2_sergioescobar_lp4;

import javax.swing.JOptionPane;

/**
 *
 * @author alexi
 */
public class MenuPrincipal_JFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal_JFrame.class.getName());

    /**
     * Creates new form MenuPrincipal_JFrame
     */
    public MenuPrincipal_JFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbtnDepositoMenu = new javax.swing.JButton();
        jbtnRetiroMenu = new javax.swing.JButton();
        jbtnSaldoMenu = new javax.swing.JButton();
        jbtnSalirMenu = new javax.swing.JButton();
        jtfMenu = new javax.swing.JTextField();
        jbtnContinuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("BANCO MEXICANO");

        jLabel2.setText("1.- ");

        jLabel3.setText("2.- ");

        jLabel4.setText("3.- ");

        jLabel5.setText("4.- ");

        jbtnDepositoMenu.setText("DEPÓSITO");
        jbtnDepositoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDepositoMenuActionPerformed(evt);
            }
        });

        jbtnRetiroMenu.setText("RETIRO");
        jbtnRetiroMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRetiroMenuActionPerformed(evt);
            }
        });

        jbtnSaldoMenu.setText("SALDO");
        jbtnSaldoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaldoMenuActionPerformed(evt);
            }
        });

        jbtnSalirMenu.setText("SALIR");
        jbtnSalirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirMenuActionPerformed(evt);
            }
        });

        jtfMenu.setEditable(false);
        jtfMenu.setBackground(new java.awt.Color(204, 204, 204));
        jtfMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMenuActionPerformed(evt);
            }
        });

        jbtnContinuar.setBackground(new java.awt.Color(153, 153, 153));
        jbtnContinuar.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jbtnContinuar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnContinuar.setText("CONTINUAR");
        jbtnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(112, 112, 112))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnDepositoMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnRetiroMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnSaldoMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnSalirMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtfMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnContinuar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jbtnDepositoMenu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jbtnRetiroMenu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jbtnSaldoMenu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jbtnSalirMenu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDepositoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDepositoMenuActionPerformed
        // TODO add your handling code here:
        jtfMenu.setText("1");
    }//GEN-LAST:event_jbtnDepositoMenuActionPerformed

    private void jbtnRetiroMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRetiroMenuActionPerformed
        // TODO add your handling code here:
        jtfMenu.setText("2");
    }//GEN-LAST:event_jbtnRetiroMenuActionPerformed
        
    private void jbtnSaldoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaldoMenuActionPerformed
        // TODO add your handling code here:
        jtfMenu.setText("3");
    }//GEN-LAST:event_jbtnSaldoMenuActionPerformed
    
    private void jbtnSalirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirMenuActionPerformed
        // TODO add your handling code here:
        jtfMenu.setText("4");
    }//GEN-LAST:event_jbtnSalirMenuActionPerformed

    private void jbtnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnContinuarActionPerformed
        // TODO add your handling code here:
        
        if (jtfMenu.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Favor de seleccionar una opción primero");
        }
        else {
        String opcion = jtfMenu.getText();
        
        switch (opcion) {
            case "1":
                Deposito_JFrame deposito = new Deposito_JFrame();
                deposito.show();
                break;
            case "2":
                Retiro_JFrame retiro = new Retiro_JFrame();
                retiro.show();
                break;
            case "3":
                Saldo_JFrame saldo = new Saldo_JFrame();
                saldo.show();
                break;
            case "4":
                this.dispose();
            default:
                JOptionPane.showMessageDialog(null, "Gracias por usar el sistema");
                break;
        }
    }
    }//GEN-LAST:event_jbtnContinuarActionPerformed

    private void jtfMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipal_JFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbtnContinuar;
    private javax.swing.JButton jbtnDepositoMenu;
    private javax.swing.JButton jbtnRetiroMenu;
    private javax.swing.JButton jbtnSaldoMenu;
    private javax.swing.JButton jbtnSalirMenu;
    private javax.swing.JTextField jtfMenu;
    // End of variables declaration//GEN-END:variables
}
