/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package actividad2_sergioescobar_lp4;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author alexi
 */
public class Retiro_JFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Retiro_JFrame.class.getName());

    /**
     * Creates new form Retiro_JFrame
     */
    public Retiro_JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfRetirar = new javax.swing.JTextField();
        jbtnSalirRetirar = new javax.swing.JButton();
        jbtnRetirar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("RETIRO");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Cantidad a retirar:");

        jtfRetirar.setText("$");
        jtfRetirar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfRetirarFocusLost(evt);
            }
        });
        jtfRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfRetirarActionPerformed(evt);
            }
        });

        jbtnSalirRetirar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jbtnSalirRetirar.setText("SALIR");
        jbtnSalirRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirRetirarActionPerformed(evt);
            }
        });

        jbtnRetirar.setBackground(new java.awt.Color(153, 153, 153));
        jbtnRetirar.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jbtnRetirar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnRetirar.setText("RETIRAR");
        jbtnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRetirarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(153, 153, 153))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(114, 114, 114))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jbtnSalirRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jbtnRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(53, 53, 53)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jtfRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSalirRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfRetirarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfRetirarFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfRetirarFocusLost

    private void jtfRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfRetirarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfRetirarActionPerformed

    private void jbtnSalirRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirRetirarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbtnSalirRetirarActionPerformed

    private void jbtnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRetirarActionPerformed
        // TODO add your handling code here:
         Connection con = null;
        PreparedStatement pstmt = null;
        
        try {
        Conexion conexion = new Conexion(); 
        con = conexion.getConnection();
        
        String texto = jtfRetirar.getText().trim().replace("$", "");
        float monto = Float.parseFloat(texto);
        
        if (monto <= 0) {
            JOptionPane.showMessageDialog(null, "El monto debe ser mayor a cero.");
            return;
        }
        
        String sql = "UPDATE cuenta SET saldo = saldo - ? WHERE id = 1";

        pstmt = con.prepareStatement(sql);
        pstmt.setFloat(1, monto);

        int filas = pstmt.executeUpdate();

        if (filas > 0) {
            JOptionPane.showMessageDialog(this, "Retiro realizado con éxito.");
            jtfRetirar.setText("$");
        } else {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al retirar en la cuenta.");
        }

        con.close();
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Ingresa un número válido en el campo de retiro.");
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al realizar el retiro: " + e.getMessage());
    }
        /*
        String opcion_retirar = jtfRetirar.getText().trim();
        String retiro_final = opcion_retirar.replace("$", "").trim();
        */
        this.dispose();
    }//GEN-LAST:event_jbtnRetirarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Retiro_JFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbtnRetirar;
    private javax.swing.JButton jbtnSalirRetirar;
    private javax.swing.JTextField jtfRetirar;
    // End of variables declaration//GEN-END:variables
}
